### ISSUE TITLE
KeyError: u'productName'

### ISSUE THREAD

**Issue by pvinis** [truebit/xUnique#53]
I'm trying to run this and I get an error. Any idea what to check?

```
xunique -v Pods/Pods.xcodeproj
Uniquify and Sort
uniquify PBXProject
uniquify PBX*Group and PBX*Reference*
uniquify XCConfigurationList
uniquify XCConfiguration
Traceback (most recent call last):
  File "/usr/local/bin/xunique", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/xUnique.py", line 546, in main
    xunique.unique_project()
  File "/usr/local/lib/python2.7/site-packages/xUnique.py", line 188, in unique_project
    self.__unique_project(self.root_hex)
  File "/usr/local/lib/python2.7/site-packages/xUnique.py", line 365, in __unique_project
    self.__set_to_result(project_hex, target_hex, cur_path_key)
  File "/usr/local/lib/python2.7/site-packages/xUnique.py", line 141, in __set_to_result
    current_path = '/'.join([str(current_node[i]) for i in current_path_key])
KeyError: u'productName'
```

**Comment by truebit** [comment]
See comment in https://github.com/truebit/xUnique/issues/54#issuecomment-842820571
